version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=BDRProject
      - POSTGRES_USER=projectuser
      - POSTGRES_PASSWORD=VP8%@TPNUn44D3Lg3Pkm
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-data:/docker-entrypoint-initdb.d/

  php-fpm:
    build: ./php-fpm
    restart: always
    hostname: php
    container_name: php
    depends_on:
      - postgres
    environment:
      - XDEBUG_CONFIG=client_port=9000
      #environment:
      #- APP_SECRET=${APP_SECRET}
      #- DATABASE_URL=${DATABASE_URL}
      #ports:
      #- ""
    volumes:
      - ./src:/var/www
      - ./logs:/var/logs
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./logs:/var/log
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/sites/:/etc/nginx/sites-available
