version: '3.8'

# https://github.com/tarohida/docker-php80-nginx-postgres-composer/blob/develop/docker-compose.yml
# https://github.com/ineat/docker-php-nginx-postgres-composer/blob/master/docker-compose.yml

services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=BDRProject
      - POSTGRES_USER=projectuser
      - POSTGRES_PASSWORD=VP8%@TPNUn44D3Lg3Pkm
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/postgres-data:/var/lib/postgresql/data
      #- ./postgres-data:/docker-entrypoint-initdb.d/

  php-fpm:
    build: ./php-fpm
    restart: always
    hostname: php
    container_name: php
    depends_on:
      - postgres
    volumes:
      - ./src:/var/www
      - ./logs:/var/logs
      #- ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
